// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDW6PyOLW6u1TnfQBp6kka36Niuv_Lgnhk',
    appId: '1:1013173236119:web:f7d020854a9e8d01af94d2',
    messagingSenderId: '1013173236119',
    projectId: 'arbeit-fesdem-project',
    authDomain: 'arbeit-fesdem-project.firebaseapp.com',
    storageBucket: 'arbeit-fesdem-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCy8w-pLg2TfSAcrWdUrqC9oqcXlfVgTEA',
    appId: '1:1013173236119:android:12502e65e7fe1402af94d2',
    messagingSenderId: '1013173236119',
    projectId: 'arbeit-fesdem-project',
    storageBucket: 'arbeit-fesdem-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpYPvCVzOKrWoQ3D_hX5GzyRqz3mDVNvU',
    appId: '1:1013173236119:ios:df826ff2baa43218af94d2',
    messagingSenderId: '1013173236119',
    projectId: 'arbeit-fesdem-project',
    storageBucket: 'arbeit-fesdem-project.appspot.com',
    iosBundleId: 'com.example.arbeit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpYPvCVzOKrWoQ3D_hX5GzyRqz3mDVNvU',
    appId: '1:1013173236119:ios:f24429108191e468af94d2',
    messagingSenderId: '1013173236119',
    projectId: 'arbeit-fesdem-project',
    storageBucket: 'arbeit-fesdem-project.appspot.com',
    iosBundleId: 'com.example.arbeit.RunnerTests',
  );
}
